nelmio_api_doc:
  documentation:
    info:
      title: Gestion d'évènements
      description: API sur la gestion d'évènements + inscription des participants aux évènements
      version: 2.0.0
    components:
      securitySchemes:
        bearerAuth:
          type: apiKey
          in: header
          name: Authorization # or another header name
    security:
      - bearerAuth: []
    paths:
      /api/login_check:
        post:
          tags:
            - Login
          summary: Authentification pour avoir le token.
          requestBody:
            content:
              application/json:
                schema:
                  properties:
                    username:
                      type: string
                    password:
                      type: string
                  type: object
          responses:
            "200":
              description: OK
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      token:
                        type: string
                      refresh_token:
                        type: string
            "401":
              description: Invalid credentials
            "400":
              description: Invalid JSON.
          security: []
  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
